import MySkills from '@/Components/MySkills';
import Navbar from '@/Components/Navbar';
import Navigation from '@/Components/Navigation';
import React from 'react';

export const metadata = {
    title: "Skills Page | FINANCIA",
    description: "Generated by create next app",
};

const page = () => {
    return (  
        <>
        <Navbar/>
        <MySkills/>
        <Navigation/> 
        </>
        
    );
}

export default page;