import MySkills from '@/Components/MySkills';
import React from 'react';

export const metadata = {
    title: "Skills Page | FINANCIA",
    description: "Generated by create next app",
};

const page = () => {
    return (  
        <MySkills/>
    );
}

export default page;