import React from 'react';

export const metadata = {
    title: "Skills Page | FINANCIA",
    description: "Generated by create next app",
  };
  

const page = () => {
    return (  
        <div>skills</div>
    );
}

export default page;