import { Inter } from "next/font/google";
import "../app/globals.css";
import Navbar from "@/Components/Navbar";
import Navigation from "@/Components/Navigation";
// import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page | FINANCIA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
