import React from 'react';

export const metadata = {
    title: "Projects Page | FINANCIA",
    description: "Generated by create next app",
  };

  
const page = () => {
    return (  
        <div>my skills</div>
    );
}

export default page;