import Register from '@/Components/Register';
import React from 'react';

export const metadata = {
    title: "Register Page | FINANCIA",
    description: "Generated by create next app",
};

const page = () => {
    return (  
        <>
            <Register/>
        </>
    );
}
 
export default page;