import React from 'react';

export const metadata = {
    title: "Register Page | FINANCIA",
    description: "Generated by create next app",
};

const page = () => {
    return (  
        <div></div>
    );
}
 
export default page;